# Generated by Django 2.2.24 on 2021-07-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210710_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='d_notes',
            field=models.TextField(blank=True, null=True, verbose_name='d_notes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
