# Generated by Django 2.2.24 on 2021-07-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210713_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
