# Generated by Django 2.2.24 on 2021-07-13 09:26

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.save_lesson_files, verbose_name='image'),
        ),
    ]
